# Generated by Django 4.2.7 on 2023-12-04 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='semester',
            field=models.IntegerField(choices=[(1, ' semester 1'), (2, ' semester 2'), (3, ' semester 3'), (4, ' semester 4'), (5, ' semester 5'), (6, ' semester 6')]),
        ),
        migrations.AlterField(
            model_name='speciality',
            name='semesters',
            field=models.IntegerField(choices=[(1, ' 2 semesters'), (2, ' 4 semesters'), (3, ' 6 semesters')]),
        ),
    ]
